spring:
  cache:
    type: redis
  redis:
    host: 119.3.185.186
    port: 6379
    password: 153246w@
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    timeout: 5000
  application:
    name: IntegrationService 
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    database: mysql     
    show-sql: true     
    hibernate:       
      ddl-auto: update
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/rabbitqueue?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  transaction:
    rollback-on-commit-failure: true
server:
  port: 1022
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 1000 #断路器请求容量阈值（异常失败个数最大值）
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1021/eureka/
tx-lcn:
  client:
    manager-address:
      - 127.0.0.1:8070