spring:
  redis:
    host: 119.3.185.186
    port: 6379
    password: 153246w@
    database: 1
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    timeout: 5000
  application:
    name: IntegrationService 
server:
  port: 1022
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 1000 #断路器请求容量阈值（异常失败个数最大值）
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1021/eureka/