spring:
  application:
    name: eureka-server
server:
  port: 1021
eureka:
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: false
    # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url: 
      defaultZone: http://eureka1:1031/eureka,http://eureka2:1041/eureka
  instance:
    hostname: eureka
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000 