spring:
  application:
    name: config-server
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest 
  cloud:
    config:
      server:
        git:
          uri: https://github.com/endloops/config-myfirst.git
          username: endloops
          password: 153246w@
          default-label: master
          search-paths: config
server:
  port: 1071
eureka:
  client:
    registry-fetch-interval-seconds: 5 #表示eureka client间隔多久去拉取服务注册信息，默认为30秒，对于api-gateway，如果要迅速获取服务注册状态，可以缩小该值，比如5秒
    service-url:
      defaultZone: http://eureka:1021/eureka
  
  instance:
    lease-expiration-duration-in-seconds: 90 #表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance。 
    lease-renewal-interval-in-seconds: 10 #表示eureka client发送心跳给server端的频率。如果在leaseExpirationDurationInSeconds后，server端没有收到client的心跳，则将摘除该instance。除此之外，如果该instance实现了HealthCheckCallback，并决定让自己unavailable的话，则该instance也不会接收到流量。
    health-check-url-path: /actuator/health
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always