spring:
  application:
    name: userInformatService
server:
  port: 1023
  tomcat:
    max-threads: 1000
    max-connections: 2000 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1021/eureka/