spring:
  application:
    name: userInformatService
  zipkin:
    base-url: http://119.3.185.186:9411
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 1023
  tomcat:
    max-threads: 1000
    max-connections: 2000 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1021/eureka/